<?php
$mailboxname = 'asddsaasd';
//$mailboxname = $hasil;
//$email= "$mailboxname@ahem.email";

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.ahem.email/api/mailbox/'."$mailboxname".'/email/'."$emailid");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '."$token";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
//echo $result;
$decode = json_decode($result);
$email = $decode->html;
curl_close ($ch);
?>